# Generated by Django 5.1 on 2024-08-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_admission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='stu_class',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
