# Generated by Django 5.1.1 on 2024-09-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_admission_stu_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='stu_class',
            field=models.CharField(max_length=100),
        ),
    ]
