# Generated by Django 5.1.1 on 2024-09-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_admission_stu_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
