# Generated by Django 5.1 on 2024-08-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Studentprofile', 'verbose_name_plural': 'Studentprofiles'},
        ),
    ]
