# Generated by Django 5.1 on 2024-08-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'verbose_name': 'Admission', 'verbose_name_plural': 'Admissions'},
        ),
    ]
